import groovy.json.*
args_map = [version:"1.$BUILD_NUMBER"]
print "Build number: "+BUILD_NUMBER
version = BUILD_NUMBER
print "version: "+version

pipeline {
  agent any
  stages {
    stage('build') {
      steps {
        sh 'tar -zcvf public.tar.gz public'
      }
    }
    stage("OCI Upload Artifact") {
        steps {
          OCIUploadArtifact(credentialsId: 'oci-compute',
          uploadArtifactDetailsList: [[artifactPath: 'public.tar.gz',
          repositoryId: 'ocid1.artifactrepository.oc1.ca-toronto-1.0.amaaaaaaeivx4paaiqfkcgy4x5plpitbkw4j7umdenljwbs2hpfdm6wkl3ca',
          repositoryType: 'GENERIC',
          sourcePath: 'public.tar.gz',
          version: "1.$BUILD_NUMBER"],
          [artifactPath: 'deployment_spec.yaml',
          repositoryId: 'ocid1.artifactrepository.oc1.ca-toronto-1.0.amaaaaaaeivx4paaiqfkcgy4x5plpitbkw4j7umdenljwbs2hpfdm6wkl3ca',
          repositoryType: 'GENERIC',
          sourcePath: 'deployment_spec.yaml',
          version: "1.$BUILD_NUMBER"]
          ])
        }
    }
    stage('Trigger Deployment') {
        steps {
          OCIDeployment(argumentVal: JsonOutput.toJson(args_map),
          credentialsId: 'oci-compute',
          displayName: "testDeployment${BUILD_NUMBER}",
          endpoint: 'https://devops.ca-toronto-1.oci.oraclecloud.com',
          pipelineId: 'ocid1.devopsdeploypipeline.oc1.ca-toronto-1.amaaaaaaeivx4paau57vqs7ab2yfpzdymm5aygab5lk2it7ie46c6vphytxq',
          pollingConfig: [timeoutSeconds: 600, "pollingIntervalSeconds" : 5], executionMode: 'SYNC'
          )
      }
    }  
  }
}
